import type { UILang } from './languages';
import type { CloudSyncStatus } from './cloudSyncController';

export interface CloudSyncStrings {
  heading: string;
  description: string;
  dataScope: string;
  status: Record<CloudSyncStatus, string>;
  lastSynced: string;
  neverSynced: string;
  connect: string;
  reconnect: string;
  syncNow: string;
  disconnect: string;
  disconnectHint: string;
  deleteCloud: string;
  conflictMessage: string;
  exportLocal: string;
  useCloudCopy: string;
  keepDeviceCopy: string;
  offlineMessage: string;
  reauthorizeMessage: string;
  unconfiguredMessage: string;
  genericError: string;
  deleteConfirmTitle: string;
  deleteConfirmDescription: string;
  cancelDelete: string;
  confirmDelete: string;
}

export const CLOUD_SYNC_STRINGS: Record<UILang, CloudSyncStrings> = {
  'zh-TW': {
    heading: 'Google Drive 雲端同步',
    description: '將完整 WordForge 備份同步到你自己的 Google Drive 隱藏應用程式資料夾。',
    dataScope: '包含設定、套牌、卡片原文、學習進度、報表與自訂圖標。',
    status: {
      unconfigured: '尚未設定',
      disconnected: '尚未連結',
      connecting: '正在連結',
      ready: '已連結',
      syncing: '同步中',
      offline: '離線，等待連線',
      reauthorize: '需要重新連結',
      conflict: '發現衝突',
      error: '同步發生錯誤',
    },
    lastSynced: '最後同步',
    neverSynced: '尚未同步',
    connect: '連結 Google Drive',
    reconnect: '重新連結 Google Drive',
    syncNow: '立即同步',
    disconnect: '斷開連結',
    disconnectHint: '斷開連結不會刪除雲端資料。',
    deleteCloud: '刪除雲端備份',
    conflictMessage: '系統沒有自動覆蓋任何一份資料；請先匯出本機備份，再依驗證指南處理分支。',
    exportLocal: '先匯出本機備份',
    useCloudCopy: '採用雲端資料',
    keepDeviceCopy: '以這台裝置為準',
    offlineMessage: '本機學習仍可繼續；恢復連線後會再次同步。',
    reauthorizeMessage: '短效授權已失效，請由按鈕重新連結。',
    unconfiguredMessage: '建置時缺少 VITE_GOOGLE_CLIENT_ID。',
    genericError: '請重新連結後再試；錯誤代碼不包含你的備份內容。',
    deleteConfirmTitle: '永久刪除 Google Drive 備份？',
    deleteConfirmDescription: '這會刪除 WordForge 建立的目前、上一版與衝突快照，保留本機資料，完成後斷開連結。',
    cancelDelete: '取消刪除',
    confirmDelete: '確認永久刪除',
  },
  en: {
    heading: 'Google Drive cloud sync',
    description: 'Sync a complete WordForge backup to your private Google Drive app-data folder.',
    dataScope: 'Includes settings, decks, card text, study progress, reports, and custom icons.',
    status: {
      unconfigured: 'Not configured',
      disconnected: 'Not connected',
      connecting: 'Connecting',
      ready: 'Connected',
      syncing: 'Syncing',
      offline: 'Offline',
      reauthorize: 'Reconnect required',
      conflict: 'Conflict found',
      error: 'Sync error',
    },
    lastSynced: 'Last synced',
    neverSynced: 'Not synced yet',
    connect: 'Connect Google Drive',
    reconnect: 'Reconnect Google Drive',
    syncNow: 'Sync now',
    disconnect: 'Disconnect',
    disconnectHint: 'Disconnecting does not delete cloud data.',
    deleteCloud: 'Delete cloud backups',
    conflictMessage: 'No copy was overwritten. Export a local backup before following the conflict guide.',
    exportLocal: 'Export local backup first',
    useCloudCopy: 'Use cloud copy',
    keepDeviceCopy: 'Keep this device',
    offlineMessage: 'Local study remains available and sync resumes after connectivity returns.',
    reauthorizeMessage: 'The short-lived authorization expired. Reconnect from the button.',
    unconfiguredMessage: 'VITE_GOOGLE_CLIENT_ID was missing at build time.',
    genericError: 'Reconnect and try again. Error codes never include backup content.',
    deleteConfirmTitle: 'Permanently delete Google Drive backups?',
    deleteConfirmDescription: 'Deletes current, previous, and conflict snapshots created by WordForge, keeps local data, then disconnects.',
    cancelDelete: 'Cancel deletion',
    confirmDelete: 'Permanently delete',
  },
  ja: {
    heading: 'Google Drive クラウド同期',
    description: 'WordForge の完全なバックアップを非表示のアプリデータ領域に同期します。',
    dataScope: '設定、デッキ、カード本文、学習進捗、レポート、カスタムアイコンを含みます。',
    status: {
      unconfigured: '未設定',
      disconnected: '未接続',
      connecting: '接続中',
      ready: '接続済み',
      syncing: '同期中',
      offline: 'オフライン',
      reauthorize: '再接続が必要',
      conflict: '競合を検出',
      error: '同期エラー',
    },
    lastSynced: '最終同期',
    neverSynced: '未同期',
    connect: 'Google Drive に接続',
    reconnect: 'Google Drive に再接続',
    syncNow: '今すぐ同期',
    disconnect: '接続解除',
    disconnectHint: '接続解除ではクラウドデータは削除されません。',
    deleteCloud: 'クラウドバックアップを削除',
    conflictMessage: 'データは上書きされていません。先にローカルバックアップを書き出してください。',
    exportLocal: '先にローカルを書き出す',
    useCloudCopy: 'クラウド版を使用',
    keepDeviceCopy: 'この端末を使用',
    offlineMessage: '学習は継続でき、接続回復後に再同期します。',
    reauthorizeMessage: '短期認証が失効しました。ボタンから再接続してください。',
    unconfiguredMessage: 'ビルド時に VITE_GOOGLE_CLIENT_ID がありません。',
    genericError: '再接続して再試行してください。',
    deleteConfirmTitle: 'Google Drive バックアップを完全に削除しますか？',
    deleteConfirmDescription: 'WordForge の現在・前回・競合スナップショットを削除し、ローカルデータを残して接続解除します。',
    cancelDelete: '削除を中止',
    confirmDelete: '完全に削除',
  },
  ko: {
    heading: 'Google Drive 클라우드 동기화',
    description: '전체 WordForge 백업을 비공개 앱 데이터 폴더에 동기화합니다.',
    dataScope: '설정, 덱, 카드 원문, 학습 진도, 보고서와 사용자 아이콘을 포함합니다.',
    status: {
      unconfigured: '설정 안 됨',
      disconnected: '연결 안 됨',
      connecting: '연결 중',
      ready: '연결됨',
      syncing: '동기화 중',
      offline: '오프라인',
      reauthorize: '재연결 필요',
      conflict: '충돌 발견',
      error: '동기화 오류',
    },
    lastSynced: '마지막 동기화',
    neverSynced: '아직 동기화 안 됨',
    connect: 'Google Drive 연결',
    reconnect: 'Google Drive 다시 연결',
    syncNow: '지금 동기화',
    disconnect: '연결 해제',
    disconnectHint: '연결 해제는 클라우드 데이터를 삭제하지 않습니다.',
    deleteCloud: '클라우드 백업 삭제',
    conflictMessage: '어느 복사본도 덮어쓰지 않았습니다. 먼저 로컬 백업을 내보내세요.',
    exportLocal: '로컬 백업 먼저 내보내기',
    useCloudCopy: '클라우드 데이터 사용',
    keepDeviceCopy: '이 기기 데이터 유지',
    offlineMessage: '로컬 학습은 계속되며 연결이 복구되면 다시 동기화합니다.',
    reauthorizeMessage: '단기 권한이 만료되었습니다. 버튼으로 다시 연결하세요.',
    unconfiguredMessage: '빌드 시 VITE_GOOGLE_CLIENT_ID가 없습니다.',
    genericError: '다시 연결한 뒤 재시도하세요.',
    deleteConfirmTitle: 'Google Drive 백업을 영구 삭제할까요?',
    deleteConfirmDescription: 'WordForge의 현재, 이전 및 충돌 스냅샷을 삭제하고 로컬 데이터는 유지한 뒤 연결을 해제합니다.',
    cancelDelete: '삭제 취소',
    confirmDelete: '영구 삭제',
  },
  de: {
    heading: 'Google-Drive-Cloud-Synchronisierung',
    description: 'Synchronisiert eine vollständige WordForge-Sicherung in den privaten App-Datenordner.',
    dataScope: 'Enthält Einstellungen, Stapel, Kartentexte, Fortschritt, Berichte und eigene Symbole.',
    status: {
      unconfigured: 'Nicht konfiguriert',
      disconnected: 'Nicht verbunden',
      connecting: 'Verbindung wird hergestellt',
      ready: 'Verbunden',
      syncing: 'Synchronisierung läuft',
      offline: 'Offline',
      reauthorize: 'Erneute Verbindung nötig',
      conflict: 'Konflikt gefunden',
      error: 'Synchronisierungsfehler',
    },
    lastSynced: 'Zuletzt synchronisiert',
    neverSynced: 'Noch nicht synchronisiert',
    connect: 'Google Drive verbinden',
    reconnect: 'Google Drive neu verbinden',
    syncNow: 'Jetzt synchronisieren',
    disconnect: 'Trennen',
    disconnectHint: 'Beim Trennen werden keine Cloud-Daten gelöscht.',
    deleteCloud: 'Cloud-Sicherungen löschen',
    conflictMessage: 'Keine Kopie wurde überschrieben. Exportieren Sie zuerst eine lokale Sicherung.',
    exportLocal: 'Lokale Sicherung zuerst exportieren',
    useCloudCopy: 'Cloud-Kopie verwenden',
    keepDeviceCopy: 'Dieses Gerät behalten',
    offlineMessage: 'Lokales Lernen bleibt möglich; nach Rückkehr der Verbindung wird erneut synchronisiert.',
    reauthorizeMessage: 'Die kurzzeitige Berechtigung ist abgelaufen. Bitte neu verbinden.',
    unconfiguredMessage: 'VITE_GOOGLE_CLIENT_ID fehlte beim Build.',
    genericError: 'Neu verbinden und erneut versuchen.',
    deleteConfirmTitle: 'Google-Drive-Sicherungen endgültig löschen?',
    deleteConfirmDescription: 'Löscht aktuelle, vorherige und Konflikt-Snapshots, behält lokale Daten und trennt danach.',
    cancelDelete: 'Löschen abbrechen',
    confirmDelete: 'Endgültig löschen',
  },
  es: {
    heading: 'Sincronización con Google Drive',
    description: 'Sincroniza una copia completa de WordForge en la carpeta privada de datos de la aplicación.',
    dataScope: 'Incluye ajustes, mazos, texto, progreso, reportes e iconos personalizados.',
    status: {
      unconfigured: 'Sin configurar',
      disconnected: 'Sin conexión',
      connecting: 'Conectando',
      ready: 'Conectado',
      syncing: 'Sincronizando',
      offline: 'Sin internet',
      reauthorize: 'Hay que reconectar',
      conflict: 'Conflicto detectado',
      error: 'Error de sincronización',
    },
    lastSynced: 'Última sincronización',
    neverSynced: 'Aún sin sincronizar',
    connect: 'Conectar Google Drive',
    reconnect: 'Reconectar Google Drive',
    syncNow: 'Sincronizar ahora',
    disconnect: 'Desconectar',
    disconnectHint: 'Desconectar no elimina los datos de la nube.',
    deleteCloud: 'Eliminar copias de la nube',
    conflictMessage: 'No se sobrescribió ninguna copia. Exporta primero una copia local.',
    exportLocal: 'Exportar primero la copia local',
    useCloudCopy: 'Usar copia de la nube',
    keepDeviceCopy: 'Conservar este dispositivo',
    offlineMessage: 'El estudio local continúa y la sincronización vuelve al recuperar internet.',
    reauthorizeMessage: 'La autorización breve caducó. Vuelve a conectar.',
    unconfiguredMessage: 'Falta VITE_GOOGLE_CLIENT_ID en la compilación.',
    genericError: 'Vuelve a conectar e inténtalo de nuevo.',
    deleteConfirmTitle: '¿Eliminar permanentemente las copias de Google Drive?',
    deleteConfirmDescription: 'Elimina instantáneas actuales, anteriores y en conflicto, conserva los datos locales y desconecta.',
    cancelDelete: 'Cancelar eliminación',
    confirmDelete: 'Eliminar permanentemente',
  },
  fr: {
    heading: 'Synchronisation Google Drive',
    description: 'Synchronise une sauvegarde WordForge complète dans le dossier privé des données d’application.',
    dataScope: 'Inclut réglages, paquets, textes, progression, rapports et icônes personnalisées.',
    status: {
      unconfigured: 'Non configuré',
      disconnected: 'Non connecté',
      connecting: 'Connexion',
      ready: 'Connecté',
      syncing: 'Synchronisation',
      offline: 'Hors ligne',
      reauthorize: 'Reconnexion requise',
      conflict: 'Conflit détecté',
      error: 'Erreur de synchronisation',
    },
    lastSynced: 'Dernière synchronisation',
    neverSynced: 'Pas encore synchronisé',
    connect: 'Connecter Google Drive',
    reconnect: 'Reconnecter Google Drive',
    syncNow: 'Synchroniser',
    disconnect: 'Déconnecter',
    disconnectHint: 'La déconnexion ne supprime pas les données cloud.',
    deleteCloud: 'Supprimer les sauvegardes cloud',
    conflictMessage: 'Aucune copie n’a été écrasée. Exportez d’abord une sauvegarde locale.',
    exportLocal: 'Exporter d’abord la sauvegarde locale',
    useCloudCopy: 'Utiliser la copie cloud',
    keepDeviceCopy: 'Garder cet appareil',
    offlineMessage: 'L’étude locale reste disponible et la synchronisation reprend au retour du réseau.',
    reauthorizeMessage: 'L’autorisation courte a expiré. Reconnectez-vous.',
    unconfiguredMessage: 'VITE_GOOGLE_CLIENT_ID manquait lors du build.',
    genericError: 'Reconnectez-vous puis réessayez.',
    deleteConfirmTitle: 'Supprimer définitivement les sauvegardes Google Drive ?',
    deleteConfirmDescription: 'Supprime les instantanés actuels, précédents et conflictuels, conserve les données locales puis déconnecte.',
    cancelDelete: 'Annuler la suppression',
    confirmDelete: 'Supprimer définitivement',
  },
  th: {
    heading: 'ซิงค์ระบบคลาวด์ Google Drive',
    description: 'ซิงค์ข้อมูลสำรอง WordForge ทั้งหมดไปยังโฟลเดอร์ข้อมูลแอปส่วนตัว',
    dataScope: 'รวมการตั้งค่า สำรับ ข้อความการ์ด ความคืบหน้า รายงาน และไอคอนที่กำหนดเอง',
    status: {
      unconfigured: 'ยังไม่ได้ตั้งค่า',
      disconnected: 'ยังไม่เชื่อมต่อ',
      connecting: 'กำลังเชื่อมต่อ',
      ready: 'เชื่อมต่อแล้ว',
      syncing: 'กำลังซิงค์',
      offline: 'ออฟไลน์',
      reauthorize: 'ต้องเชื่อมต่อใหม่',
      conflict: 'พบข้อมูลขัดแย้ง',
      error: 'ซิงค์ผิดพลาด',
    },
    lastSynced: 'ซิงค์ล่าสุด',
    neverSynced: 'ยังไม่เคยซิงค์',
    connect: 'เชื่อมต่อ Google Drive',
    reconnect: 'เชื่อมต่อ Google Drive ใหม่',
    syncNow: 'ซิงค์ตอนนี้',
    disconnect: 'ยกเลิกการเชื่อมต่อ',
    disconnectHint: 'การยกเลิกการเชื่อมต่อจะไม่ลบข้อมูลคลาวด์',
    deleteCloud: 'ลบข้อมูลสำรองคลาวด์',
    conflictMessage: 'ระบบไม่ได้เขียนทับข้อมูลชุดใด โปรดส่งออกข้อมูลสำรองในเครื่องก่อน',
    exportLocal: 'ส่งออกข้อมูลในเครื่องก่อน',
    useCloudCopy: 'ใช้ข้อมูลจากคลาวด์',
    keepDeviceCopy: 'ใช้ข้อมูลในอุปกรณ์นี้',
    offlineMessage: 'ยังเรียนในเครื่องได้ และจะซิงค์อีกครั้งเมื่อเครือข่ายกลับมา',
    reauthorizeMessage: 'สิทธิ์ระยะสั้นหมดอายุ โปรดเชื่อมต่อใหม่',
    unconfiguredMessage: 'ไม่มี VITE_GOOGLE_CLIENT_ID ตอน build',
    genericError: 'โปรดเชื่อมต่อใหม่แล้วลองอีกครั้ง',
    deleteConfirmTitle: 'ลบข้อมูลสำรอง Google Drive ถาวรหรือไม่',
    deleteConfirmDescription: 'ลบ snapshot ปัจจุบัน ก่อนหน้า และที่ขัดแย้ง เก็บข้อมูลในเครื่องไว้ แล้วตัดการเชื่อมต่อ',
    cancelDelete: 'ยกเลิกการลบ',
    confirmDelete: 'ลบถาวร',
  },
};
