import type { DeckType } from './types';
import type { UILang } from './languages';

export interface ListeningStrings {
  title: string;
  entry: string;
  doesNotAffectProgress: string;
  sourceToday: string;
  sourceAll: string;
  orderSequential: string;
  orderShuffle: string;
  loopPlaylist: string;
  wordRepeats: string;
  phraseRepeats: string;
  exampleRepeats: string;
  previous: string;
  play: string;
  pause: string;
  next: string;
  queue: string;
  closeQueue: string;
  unsupported: string;
  backgroundBestEffort: string;
  retry: string;
  skipCard: string;
  back: string;
  empty: string;
  enableOneRepeat: string;
  paused: string;
  completed: string;
  interrupted: string;
  loading: string;
  playbackError: string;
  frontStatus: string;
  exampleStatus: string;
  cardProgress: string;
  audioSettings: string;
  closeAudioSettings: string;
  automaticVoice: string;
  rate: string;
  preferredVoice: string;
  showAllVoices: string;
  showCompatibleVoices: string;
  previewVoice: string;
  previewing: string;
  resetAudio: string;
  voicesLoading: string;
  voicesUnavailable: string;
  refreshVoices: string;
  voiceUnavailable: string;
  localVoice: string;
  networkVoice: string;
  fallbackForLanguage: string;
  previewError: string;
}

type ListeningAudioStrings = Pick<ListeningStrings,
  | 'audioSettings' | 'closeAudioSettings' | 'automaticVoice' | 'rate'
  | 'preferredVoice' | 'showAllVoices' | 'showCompatibleVoices'
  | 'previewVoice' | 'previewing' | 'resetAudio' | 'voicesLoading'
  | 'voicesUnavailable' | 'refreshVoices' | 'voiceUnavailable' | 'localVoice'
  | 'networkVoice' | 'fallbackForLanguage' | 'previewError'>;

const LISTENING_AUDIO_STRINGS: Record<UILang, ListeningAudioStrings> = {
  'zh-TW': {
    audioSettings: '音訊設定',
    closeAudioSettings: '關閉音訊設定',
    automaticVoice: '自動推薦',
    rate: '播放速度',
    preferredVoice: '首選聲音',
    showAllVoices: '顯示全部聲音',
    showCompatibleVoices: '只顯示相容聲音',
    previewVoice: '試聽目前卡片',
    previewing: '正在試聽',
    resetAudio: '恢復音訊預設',
    voicesLoading: '正在載入聲音清單…',
    voicesUnavailable: '目前無法取得聲音清單',
    refreshVoices: '重新載入聲音',
    voiceUnavailable: '目前無法使用',
    localVoice: '本機聲音',
    networkVoice: '可能需要網路',
    fallbackForLanguage: '目前使用 {language} 自動備援',
    previewError: '試聽失敗：{error}',
  },
  en: {
    audioSettings: 'Audio settings',
    closeAudioSettings: 'Close audio settings',
    automaticVoice: 'Automatic',
    rate: 'Playback speed',
    preferredVoice: 'Preferred voice',
    showAllVoices: 'Show all voices',
    showCompatibleVoices: 'Show compatible voices',
    previewVoice: 'Preview current card',
    previewing: 'Previewing',
    resetAudio: 'Reset audio defaults',
    voicesLoading: 'Loading voices…',
    voicesUnavailable: 'Voice list is currently unavailable',
    refreshVoices: 'Refresh voices',
    voiceUnavailable: 'Currently unavailable',
    localVoice: 'On-device voice',
    networkVoice: 'May require network',
    fallbackForLanguage: 'Using automatic {language} fallback',
    previewError: 'Preview failed: {error}',
  },
  ja: {
    audioSettings: '音声設定',
    closeAudioSettings: '音声設定を閉じる',
    automaticVoice: '自動選択',
    rate: '再生速度',
    preferredVoice: '優先音声',
    showAllVoices: 'すべての音声を表示',
    showCompatibleVoices: '対応音声のみ表示',
    previewVoice: '現在のカードを試聴',
    previewing: '試聴中',
    resetAudio: '音声設定を初期化',
    voicesLoading: '音声一覧を読み込み中…',
    voicesUnavailable: '音声一覧を取得できません',
    refreshVoices: '音声を再読み込み',
    voiceUnavailable: '現在利用できません',
    localVoice: '端末内音声',
    networkVoice: 'ネット接続が必要な場合あり',
    fallbackForLanguage: '{language} の自動音声を使用中',
    previewError: '試聴に失敗しました：{error}',
  },
  ko: {
    audioSettings: '오디오 설정',
    closeAudioSettings: '오디오 설정 닫기',
    automaticVoice: '자동 추천',
    rate: '재생 속도',
    preferredVoice: '선호 음성',
    showAllVoices: '모든 음성 표시',
    showCompatibleVoices: '호환 음성만 표시',
    previewVoice: '현재 카드 미리 듣기',
    previewing: '미리 듣는 중',
    resetAudio: '오디오 기본값 복원',
    voicesLoading: '음성 목록 불러오는 중…',
    voicesUnavailable: '현재 음성 목록을 가져올 수 없습니다',
    refreshVoices: '음성 다시 불러오기',
    voiceUnavailable: '현재 사용할 수 없음',
    localVoice: '기기 내 음성',
    networkVoice: '네트워크가 필요할 수 있음',
    fallbackForLanguage: '현재 {language} 자동 대체 음성 사용 중',
    previewError: '미리 듣기 실패: {error}',
  },
  de: {
    audioSettings: 'Audioeinstellungen',
    closeAudioSettings: 'Audioeinstellungen schließen',
    automaticVoice: 'Automatisch',
    rate: 'Wiedergabegeschwindigkeit',
    preferredVoice: 'Bevorzugte Stimme',
    showAllVoices: 'Alle Stimmen anzeigen',
    showCompatibleVoices: 'Kompatible Stimmen anzeigen',
    previewVoice: 'Aktuelle Karte vorhören',
    previewing: 'Vorschau läuft',
    resetAudio: 'Audio zurücksetzen',
    voicesLoading: 'Stimmen werden geladen…',
    voicesUnavailable: 'Stimmenliste ist derzeit nicht verfügbar',
    refreshVoices: 'Stimmen neu laden',
    voiceUnavailable: 'Derzeit nicht verfügbar',
    localVoice: 'Lokale Stimme',
    networkVoice: 'Benötigt möglicherweise Internet',
    fallbackForLanguage: 'Automatische {language}-Ersatzstimme aktiv',
    previewError: 'Vorschau fehlgeschlagen: {error}',
  },
  es: {
    audioSettings: 'Ajustes de audio',
    closeAudioSettings: 'Cerrar ajustes de audio',
    automaticVoice: 'Automática',
    rate: 'Velocidad de reproducción',
    preferredVoice: 'Voz preferida',
    showAllVoices: 'Mostrar todas las voces',
    showCompatibleVoices: 'Mostrar voces compatibles',
    previewVoice: 'Probar la tarjeta actual',
    previewing: 'Reproduciendo prueba',
    resetAudio: 'Restablecer audio',
    voicesLoading: 'Cargando voces…',
    voicesUnavailable: 'La lista de voces no está disponible',
    refreshVoices: 'Recargar voces',
    voiceUnavailable: 'No disponible actualmente',
    localVoice: 'Voz del dispositivo',
    networkVoice: 'Puede requerir conexión',
    fallbackForLanguage: 'Usando alternativa automática para {language}',
    previewError: 'Falló la prueba: {error}',
  },
  fr: {
    audioSettings: 'Réglages audio',
    closeAudioSettings: 'Fermer les réglages audio',
    automaticVoice: 'Automatique',
    rate: 'Vitesse de lecture',
    preferredVoice: 'Voix préférée',
    showAllVoices: 'Afficher toutes les voix',
    showCompatibleVoices: 'Afficher les voix compatibles',
    previewVoice: 'Écouter la carte actuelle',
    previewing: 'Aperçu en cours',
    resetAudio: 'Réinitialiser l’audio',
    voicesLoading: 'Chargement des voix…',
    voicesUnavailable: 'La liste des voix est indisponible',
    refreshVoices: 'Recharger les voix',
    voiceUnavailable: 'Actuellement indisponible',
    localVoice: 'Voix locale',
    networkVoice: 'Peut nécessiter Internet',
    fallbackForLanguage: 'Voix automatique {language} utilisée',
    previewError: 'Échec de l’aperçu : {error}',
  },
  th: {
    audioSettings: 'การตั้งค่าเสียง',
    closeAudioSettings: 'ปิดการตั้งค่าเสียง',
    automaticVoice: 'แนะนำอัตโนมัติ',
    rate: 'ความเร็วในการเล่น',
    preferredVoice: 'เสียงที่ต้องการ',
    showAllVoices: 'แสดงเสียงทั้งหมด',
    showCompatibleVoices: 'แสดงเสียงที่เข้ากันได้',
    previewVoice: 'ทดลองฟังบัตรปัจจุบัน',
    previewing: 'กำลังทดลองฟัง',
    resetAudio: 'คืนค่าเสียงเริ่มต้น',
    voicesLoading: 'กำลังโหลดรายการเสียง…',
    voicesUnavailable: 'ไม่สามารถรับรายการเสียงได้ในขณะนี้',
    refreshVoices: 'โหลดรายการเสียงใหม่',
    voiceUnavailable: 'ไม่พร้อมใช้งานในขณะนี้',
    localVoice: 'เสียงในอุปกรณ์',
    networkVoice: 'อาจต้องใช้อินเทอร์เน็ต',
    fallbackForLanguage: 'กำลังใช้เสียงสำรองอัตโนมัติสำหรับ {language}',
    previewError: 'ทดลองฟังไม่สำเร็จ: {error}',
  },
};

export const LISTENING_STRINGS: Record<UILang, ListeningStrings> = {
  'zh-TW': {
    ...LISTENING_AUDIO_STRINGS['zh-TW'],
    title: '連續聆聽',
    entry: '進入聆聽模式',
    doesNotAffectProgress: '只播放語音，不會改動學習進度',
    sourceToday: '今日清單',
    sourceAll: '全部卡片',
    orderSequential: '依序',
    orderShuffle: '隨機',
    loopPlaylist: '循環整份清單',
    wordRepeats: '單字次數',
    phraseRepeats: '片語次數',
    exampleRepeats: '例句次數',
    previous: '上一張',
    play: '播放',
    pause: '暫停',
    next: '下一張',
    queue: '播放清單',
    closeQueue: '關閉播放清單',
    unsupported: '此瀏覽器不支援語音播放',
    backgroundBestEffort: '背景與鎖屏播放取決於瀏覽器及作業系統，無法保證不中斷。',
    retry: '重試這一遍',
    skipCard: '跳過這張',
    back: '返回學習中心',
    empty: '目前清單沒有可播放的卡片',
    enableOneRepeat: '請至少將單字／片語或例句次數設為 1。',
    paused: '已暫停',
    completed: '播放完成',
    interrupted: '瀏覽器已中斷語音；按播放會從目前這一遍重新開始。',
    loading: '正在建立播放清單…',
    playbackError: '語音播放失敗',
    frontStatus: '正在朗讀主內容・第 {current} / {total} 遍',
    exampleStatus: '正在朗讀例句・第 {current} / {total} 遍',
    cardProgress: '第 {current} / {total} 張',
  },
  en: {
    ...LISTENING_AUDIO_STRINGS.en,
    title: 'Continuous Listening',
    entry: 'Open Listening Mode',
    doesNotAffectProgress: 'Audio only — your learning progress will not change',
    sourceToday: "Today's List",
    sourceAll: 'All Cards',
    orderSequential: 'Sequential',
    orderShuffle: 'Shuffle',
    loopPlaylist: 'Loop playlist',
    wordRepeats: 'Word repeats',
    phraseRepeats: 'Phrase repeats',
    exampleRepeats: 'Example repeats',
    previous: 'Previous',
    play: 'Play',
    pause: 'Pause',
    next: 'Next',
    queue: 'Playlist',
    closeQueue: 'Close playlist',
    unsupported: 'Speech playback is not supported by this browser',
    backgroundBestEffort: 'Background and lock-screen playback depend on your browser and operating system.',
    retry: 'Retry this repetition',
    skipCard: 'Skip card',
    back: 'Back to Learning Center',
    empty: 'There are no playable cards in this list',
    enableOneRepeat: 'Set either the main text or example repeats to at least 1.',
    paused: 'Paused',
    completed: 'Playback complete',
    interrupted: 'The browser interrupted speech. Play restarts the current repetition.',
    loading: 'Building playlist…',
    playbackError: 'Speech playback failed',
    frontStatus: 'Reading main text · {current} / {total}',
    exampleStatus: 'Reading example · {current} / {total}',
    cardProgress: 'Card {current} / {total}',
  },
  ja: {
    ...LISTENING_AUDIO_STRINGS.ja,
    title: '連続リスニング',
    entry: 'リスニングモードへ',
    doesNotAffectProgress: '音声のみ再生し、学習進捗は変更しません',
    sourceToday: '今日のリスト',
    sourceAll: 'すべてのカード',
    orderSequential: '順番',
    orderShuffle: 'シャッフル',
    loopPlaylist: 'リストを繰り返す',
    wordRepeats: '単語の回数',
    phraseRepeats: 'フレーズの回数',
    exampleRepeats: '例文の回数',
    previous: '前へ',
    play: '再生',
    pause: '一時停止',
    next: '次へ',
    queue: '再生リスト',
    closeQueue: '再生リストを閉じる',
    unsupported: 'このブラウザは音声再生に対応していません',
    backgroundBestEffort: 'バックグラウンドとロック画面での再生は端末環境に依存します。',
    retry: 'この回を再試行',
    skipCard: 'このカードをスキップ',
    back: '学習センターへ戻る',
    empty: '再生できるカードがありません',
    enableOneRepeat: '単語／フレーズまたは例文を 1 回以上に設定してください。',
    paused: '一時停止中',
    completed: '再生完了',
    interrupted: 'ブラウザが音声を中断しました。再生すると現在の回を最初から読みます。',
    loading: '再生リストを作成中…',
    playbackError: '音声再生に失敗しました',
    frontStatus: 'メインを再生中・{current} / {total} 回',
    exampleStatus: '例文を再生中・{current} / {total} 回',
    cardProgress: '{current} / {total} 枚目',
  },
  ko: {
    ...LISTENING_AUDIO_STRINGS.ko,
    title: '연속 듣기',
    entry: '듣기 모드 열기',
    doesNotAffectProgress: '음성만 재생하며 학습 진도는 변경하지 않습니다',
    sourceToday: '오늘 목록',
    sourceAll: '모든 카드',
    orderSequential: '순서대로',
    orderShuffle: '무작위',
    loopPlaylist: '전체 목록 반복',
    wordRepeats: '단어 반복',
    phraseRepeats: '구문 반복',
    exampleRepeats: '예문 반복',
    previous: '이전',
    play: '재생',
    pause: '일시 정지',
    next: '다음',
    queue: '재생 목록',
    closeQueue: '재생 목록 닫기',
    unsupported: '이 브라우저는 음성 재생을 지원하지 않습니다',
    backgroundBestEffort: '백그라운드 및 잠금 화면 재생은 브라우저와 운영체제에 따라 달라집니다.',
    retry: '현재 반복 다시 시도',
    skipCard: '카드 건너뛰기',
    back: '학습 센터로',
    empty: '재생할 수 있는 카드가 없습니다',
    enableOneRepeat: '단어／구문 또는 예문 반복을 1 이상으로 설정하세요.',
    paused: '일시 정지됨',
    completed: '재생 완료',
    interrupted: '브라우저가 음성을 중단했습니다. 재생하면 현재 반복을 처음부터 시작합니다.',
    loading: '재생 목록 만드는 중…',
    playbackError: '음성 재생 실패',
    frontStatus: '주요 내용 재생 중 · {current} / {total}',
    exampleStatus: '예문 재생 중 · {current} / {total}',
    cardProgress: '{current} / {total} 카드',
  },
  de: {
    ...LISTENING_AUDIO_STRINGS.de,
    title: 'Fortlaufendes Hören',
    entry: 'Hörmodus öffnen',
    doesNotAffectProgress: 'Nur Audio – der Lernfortschritt bleibt unverändert',
    sourceToday: 'Heutige Liste',
    sourceAll: 'Alle Karten',
    orderSequential: 'Der Reihe nach',
    orderShuffle: 'Zufällig',
    loopPlaylist: 'Liste wiederholen',
    wordRepeats: 'Wortwiederholungen',
    phraseRepeats: 'Phrasenwiederholungen',
    exampleRepeats: 'Beispielwiederholungen',
    previous: 'Zurück',
    play: 'Abspielen',
    pause: 'Pause',
    next: 'Weiter',
    queue: 'Wiedergabeliste',
    closeQueue: 'Wiedergabeliste schließen',
    unsupported: 'Dieser Browser unterstützt keine Sprachausgabe',
    backgroundBestEffort: 'Hintergrund- und Sperrbildschirmwiedergabe hängen von Browser und Betriebssystem ab.',
    retry: 'Wiederholung erneut versuchen',
    skipCard: 'Karte überspringen',
    back: 'Zurück zum Lernzentrum',
    empty: 'Diese Liste enthält keine abspielbaren Karten',
    enableOneRepeat: 'Mindestens eine Wiederholungszahl muss 1 oder höher sein.',
    paused: 'Pausiert',
    completed: 'Wiedergabe beendet',
    interrupted: 'Der Browser hat die Sprachausgabe unterbrochen. Abspielen startet die aktuelle Wiederholung neu.',
    loading: 'Wiedergabeliste wird erstellt…',
    playbackError: 'Sprachausgabe fehlgeschlagen',
    frontStatus: 'Hauptinhalt · {current} / {total}',
    exampleStatus: 'Beispiel · {current} / {total}',
    cardProgress: 'Karte {current} / {total}',
  },
  es: {
    ...LISTENING_AUDIO_STRINGS.es,
    title: 'Escucha continua',
    entry: 'Abrir modo de escucha',
    doesNotAffectProgress: 'Solo audio; el progreso de aprendizaje no cambia',
    sourceToday: 'Lista de hoy',
    sourceAll: 'Todas las tarjetas',
    orderSequential: 'En orden',
    orderShuffle: 'Aleatorio',
    loopPlaylist: 'Repetir lista',
    wordRepeats: 'Repeticiones de palabra',
    phraseRepeats: 'Repeticiones de frase',
    exampleRepeats: 'Repeticiones de ejemplo',
    previous: 'Anterior',
    play: 'Reproducir',
    pause: 'Pausar',
    next: 'Siguiente',
    queue: 'Lista de reproducción',
    closeQueue: 'Cerrar lista',
    unsupported: 'Este navegador no admite la reproducción de voz',
    backgroundBestEffort: 'La reproducción en segundo plano y con pantalla bloqueada depende del sistema.',
    retry: 'Reintentar esta repetición',
    skipCard: 'Saltar tarjeta',
    back: 'Volver al centro de aprendizaje',
    empty: 'No hay tarjetas reproducibles en esta lista',
    enableOneRepeat: 'Configura al menos una repetición en 1 o más.',
    paused: 'En pausa',
    completed: 'Reproducción terminada',
    interrupted: 'El navegador interrumpió la voz. Reproducir reinicia la repetición actual.',
    loading: 'Creando lista…',
    playbackError: 'Falló la reproducción de voz',
    frontStatus: 'Contenido principal · {current} / {total}',
    exampleStatus: 'Ejemplo · {current} / {total}',
    cardProgress: 'Tarjeta {current} / {total}',
  },
  fr: {
    ...LISTENING_AUDIO_STRINGS.fr,
    title: 'Écoute continue',
    entry: "Ouvrir le mode d'écoute",
    doesNotAffectProgress: "Audio uniquement — la progression d'apprentissage ne change pas",
    sourceToday: "Liste d'aujourd'hui",
    sourceAll: 'Toutes les cartes',
    orderSequential: "Dans l'ordre",
    orderShuffle: 'Aléatoire',
    loopPlaylist: 'Répéter la liste',
    wordRepeats: 'Répétitions du mot',
    phraseRepeats: 'Répétitions de la phrase',
    exampleRepeats: "Répétitions de l'exemple",
    previous: 'Précédente',
    play: 'Lire',
    pause: 'Pause',
    next: 'Suivante',
    queue: 'Liste de lecture',
    closeQueue: 'Fermer la liste',
    unsupported: 'Ce navigateur ne prend pas en charge la synthèse vocale',
    backgroundBestEffort: "La lecture en arrière-plan dépend du navigateur et du système d'exploitation.",
    retry: 'Réessayer cette répétition',
    skipCard: 'Passer la carte',
    back: "Retour au centre d'apprentissage",
    empty: 'Aucune carte ne peut être lue dans cette liste',
    enableOneRepeat: 'Réglez au moins une répétition sur 1 ou plus.',
    paused: 'En pause',
    completed: 'Lecture terminée',
    interrupted: 'Le navigateur a interrompu la voix. Lire recommence la répétition actuelle.',
    loading: 'Création de la liste…',
    playbackError: 'Échec de la synthèse vocale',
    frontStatus: 'Contenu principal · {current} / {total}',
    exampleStatus: 'Exemple · {current} / {total}',
    cardProgress: 'Carte {current} / {total}',
  },
  th: {
    ...LISTENING_AUDIO_STRINGS.th,
    title: 'ฟังต่อเนื่อง',
    entry: 'เปิดโหมดฟัง',
    doesNotAffectProgress: 'เล่นเฉพาะเสียงและไม่เปลี่ยนความคืบหน้าการเรียน',
    sourceToday: 'รายการวันนี้',
    sourceAll: 'การ์ดทั้งหมด',
    orderSequential: 'ตามลำดับ',
    orderShuffle: 'สุ่ม',
    loopPlaylist: 'วนทั้งรายการ',
    wordRepeats: 'จำนวนคำศัพท์',
    phraseRepeats: 'จำนวนวลี',
    exampleRepeats: 'จำนวนประโยคตัวอย่าง',
    previous: 'ก่อนหน้า',
    play: 'เล่น',
    pause: 'หยุดชั่วคราว',
    next: 'ถัดไป',
    queue: 'รายการเล่น',
    closeQueue: 'ปิดรายการเล่น',
    unsupported: 'เบราว์เซอร์นี้ไม่รองรับการอ่านออกเสียง',
    backgroundBestEffort: 'การเล่นเบื้องหลังและหน้าจอล็อกขึ้นอยู่กับเบราว์เซอร์และระบบปฏิบัติการ',
    retry: 'ลองรอบนี้อีกครั้ง',
    skipCard: 'ข้ามการ์ด',
    back: 'กลับศูนย์การเรียน',
    empty: 'ไม่มีการ์ดที่เล่นได้ในรายการนี้',
    enableOneRepeat: 'ตั้งจำนวนคำ／วลีหรือประโยคตัวอย่างอย่างน้อย 1',
    paused: 'หยุดชั่วคราว',
    completed: 'เล่นจบแล้ว',
    interrupted: 'เบราว์เซอร์หยุดเสียง กดเล่นเพื่อเริ่มรอบปัจจุบันใหม่',
    loading: 'กำลังสร้างรายการเล่น…',
    playbackError: 'เล่นเสียงไม่สำเร็จ',
    frontStatus: 'กำลังอ่านเนื้อหาหลัก · {current} / {total}',
    exampleStatus: 'กำลังอ่านประโยคตัวอย่าง · {current} / {total}',
    cardProgress: 'การ์ด {current} / {total}',
  },
};

export function formatListeningString(
  template: string,
  values: Record<string, string | number>,
): string {
  return Object.entries(values).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    template,
  );
}

export function getFrontRepeatLabel(
  strings: ListeningStrings,
  mode: DeckType,
): string {
  return mode === 'phrase' ? strings.phraseRepeats : strings.wordRepeats;
}
